#!/usr/bin/env bash

if [ ! -d "node_modules" ]; then
    npm install
    grunt install
fi

if [ "$1" == "test" ]; then
    echo Testing Duckling
    gulp
    (cd build/spec; ../../node_modules/nw/bin/nw) &
    gulp watch
else
    gulp
    (cd build; ../node_modules/nw/bin/nw) &
    gulp watch
fi
