#!/usr/bin/env bash

if [ ! -d "node_modules" ]; then
    npm install
    grunt install
fi

if [ "$1" == "test" ]; then
    echo Testing Duckling
    grunt
    (cd build/spec; ../../node_modules/nw/bin/nw)
else
    grunt
    (cd build; ../node_modules/nw/bin/nw)
fi
